import torch.nn as nn
from model.acff import ACFF

debug = False

class ErNET(nn.Module):
    def __init__(self):
        super(ErNET, self).__init__()

        self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, stride=2, padding=1, bias=False)
        self.batch_norm1 = nn.BatchNorm2d(16)
        self.leaky_relu1 = nn.LeakyReLU(0.01)
        self.conv_red1 = nn.Conv2d(in_channels=16, out_channels=8, kernel_size=1, stride=1, padding=0, bias=False)
        self.batch_norm_red1 = nn.BatchNorm2d(8)
        self.leaky_relu_red1 = nn.LeakyReLU(0.01)
        self.acff1 = ACFF(8, 64)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv_red2 = nn.Conv2d(in_channels=64, out_channels=32, kernel_size=1, stride=1, padding=0, bias=False)
        self.batch_norm_red2 = nn.BatchNorm2d(32)
        self.leaky_relu_red2 = nn.LeakyReLU(0.01)
        self.acff2 = ACFF(32, 96)
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv_red3 = nn.Conv2d(in_channels=96, out_channels=48, kernel_size=1, stride=1, padding=0, bias=False)
        self.batch_norm_red3 = nn.BatchNorm2d(48)
        self.leaky_relu_red3 = nn.LeakyReLU(0.01)
        self.acff3 = ACFF(48, 128)
        self.pool3 = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv_red4 = nn.Conv2d(in_channels=128, out_channels=64, kernel_size=1, stride=1, padding=0, bias=False)
        self.batch_norm_red4 = nn.BatchNorm2d(64)
        self.leaky_relu_red4 = nn.LeakyReLU(0.01)
        self.acff4 = ACFF(64, 128)
        self.drop4 = nn.Dropout(0.2)
        self.conv_red5 = nn.Conv2d(in_channels=128, out_channels=64, kernel_size=1, stride=1, padding=0, bias=False)
        self.batch_norm_red5 = nn.BatchNorm2d(64)
        self.leaky_relu_red5 = nn.LeakyReLU(0.01)
        self.acff5 = ACFF(64, 128)
        self.drop5 = nn.Dropout(0.2)
        self.conv_red6 = nn.Conv2d(in_channels=128, out_channels=64, kernel_size=1, stride=1, padding=0, bias=False)
        self.batch_norm_red6 = nn.BatchNorm2d(64)
        self.leaky_relu_red6 = nn.LeakyReLU(0.01)
        self.acff6 = ACFF(64, 256)
        self.conv2 = nn.Conv2d(in_channels=256, out_channels=5, kernel_size=1, stride=1, padding=0, bias=False)
        self.batch_norm_last = nn.BatchNorm2d(5)
        self.leaky_relu_last = nn.LeakyReLU(0.01)
        self.globalpool = nn.AvgPool2d(kernel_size=5, stride=1, padding=0)
        self.fc = nn.Linear(11 * 11 * 5, 5)
        self.soft = nn.Softmax(dim=1)

    def forward(self, x):
        out = self.conv1(x)
        out = self.batch_norm1(out)
        out = self.leaky_relu1(out)
        out = self.conv_red1(out)
        out = self.batch_norm_red1(out)
        out = self.leaky_relu_red1(out)
        out = self.acff1(out)
        out = self.pool1(out)
        out = self.conv_red2(out)
        out = self.batch_norm_red2(out)
        out = self.leaky_relu_red2(out)
        out = self.acff2(out)
        out = self.pool2(out)
        out = self.conv_red3(out)
        out = self.batch_norm_red3(out)
        out = self.leaky_relu_red3(out)
        out = self.acff3(out)
        out = self.pool3(out)
        out = self.conv_red4(out)
        out = self.batch_norm_red4(out)
        out = self.leaky_relu_red4(out)
        out = self.acff4(out)
        out = self.drop4(out)
        out = self.conv_red5(out)
        out = self.batch_norm_red5(out)
        out = self.leaky_relu_red5(out)
        out = self.acff5(out)
        out = self.drop5(out)
        out = self.conv_red6(out)
        out = self.batch_norm_red6(out)
        out = self.leaky_relu_red6(out)
        out = self.acff6(out)
        out = self.conv2(out)
        out = self.batch_norm_last(out)
        out = self.leaky_relu_last(out)
        out = self.globalpool(out)

        if debug:
            print('Shape of globalpool output: ', out.shape)

        out = out.view(-1, 11 * 11 * 5)
        out = self.fc(out)
        out = self.soft(out)

        if debug:
            print('Final shape of ErNET Output: ', out.shape)

        return out
